version: '3.8'

services:

  task-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_service
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: mysql-volume
        target: /var/lib/mysql
      - type: bind
        source: ./task_service/src/main/resources/db_init
        target: /docker-entrypoint-initdb.d
    networks:
      - backend

  task-app:
    build: ./task_service/
    ports:
      - "49160:8080"
    depends_on:
      - task-db
    networks:
      - backend

  web-server:
    build: web_server/
    ports:
      - "8080:8080"
    depends_on:
      - task-app
    networks:
      - backend

volumes:
  mysql-volume:

networks:
  backend:
    driver: bridge